apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tg7lvmdy5-nodejs
  janus-idp.io/tekton: tg7lvmdy5-nodejs
  backstage.io/kubernetes-id: tg7lvmdy5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tg7lvmdy5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
